export enum AudioMixerCommand {
  GetMixerParm = 0x50,
  RetSetMixerParm = 0x51,
  GetMixerPortParm = 0x52,
  RetSetMixerPortParm = 0x53,
  GetMixerInputParm = 0x54,
  RetSetMixerInputParm = 0x55,
  GetMixerOutputParm = 0x56,
  RetSetMixerOutputParm = 0x57,
  GetMixerInputControl = 0x58,
  RetMixerInputControl = 0x59,
  GetMixerOutputControl = 0x5a,
  RetMixerOutputControl = 0x5b,
  GetMixerInputControlValue = 0x5c,
  RetSetMixerInputControlValue = 0x5d,
  GetMixerOutputControlValue = 0x5e,
  RetSetMixerOutputControlValue = 0x5f,
  GetMixerMeterValue = 0x60,
  RetMixerMeterValue = 0x61,
}
