export enum MidiCommand {
  GetMIDIInfo = 0x20,
  RetSetMIDIInfo = 0x21,
  GetMIDIPortInfo = 0x22,
  RetSetMIDIPortInfo = 0x23,
  GetMIDIPortFilter = 0x24,
  RetSetMIDIPortFilter = 0x25,
  GetMIDIPortRemap = 0x26,
  RetSetMIDIPortRemap = 0x27,
  GetMIDIPortRoute = 0x28,
  RetSetMIDIPortRoute = 0x29,
  GetMIDIPortDetail = 0x2a,
  RetSetMIDIPortDetail = 0x2b,
  GetRTPMIDIConnectionDetail = 0x2c,
  RetRTPMIDIConnectionDetail = 0x2d,
  GetUSBHostMIDIDeviceDetail = 0x2e,
  RetUSBHostMIDIDeviceDetail = 0x2f,
  GetMIDIMonitor = 0x70,
  RetMIDIMonitor = 0x71,
  GetRTPMIDIConnectionParm = 0x7e,
  RetRTPMIDIConnectionParm = 0x7f,
}
